### ISSUE TITLE
No trailing ws* assumed for the top rule?

### ISSUE THREAD

**Issue by agentzh** [ingydotnet/pegex-pm#31]
Firstly I must thank you for the excellent work on Pegex! It has wonderful performance as compared to Parse::RecDescent and Regexp::Grammars.

The question I have right now is that why we don't have trailing `ws*` assumed for the top rule. Take the stock `calculator1.pl` sample script in the git repos as an example, trailing spaces fail the parser:

```
$ echo ' 1 + 2 ' | perl calculator1.pl

Error parsing Pegex document:
  msg:      Parse document failed for some reason
  line:     1
  column:   7
  context:   1 + 2
                  ^
  position: 6 (6 pre-lookahead)
 at calculator1.pl line 50.
...
```

I know we can explicitly add a `ws*` after the top rule, but it'll be more convenient if the default behavior can take care of that for us. What do you think? ;)

**Comment by agentzh** [comment]
Oh, never mind. After reading about the `/- ... -/` whitespace control notation in the docs, this issue in `calculator1.pl` can be simply fixed by changing the grammar to something like this:

```
expr: add-sub
add-sub: mul-div+ % /- ( [ '+-' ] ) /
mul-div: power+ % /- ([ '*/' ] ) /
power: token+ % /- '^' /
token: /- '(' -/ expr /- ')' -/ | number
number: /- ( '-'? DIGIT+ ) -/
```

Sorry for the noise :)

**Comment by ingydotnet** [comment]
@agentzh Thanks. I mean you are welcome. I mean I'm glad you like it.

You should join us in #pegex on irc.freenode.net

I'm really interested in what you are using Pegex for. I can also offer help.

Cheers, Ingy

**Comment by ingydotnet** [comment]
@agentzh thanks for dropping by IRC. I looked at openresty/opsboy and I see the PRD grammar, but I don't know how to run the tests, and I don't see any Pegex yet.

Drop by again in 9 hours or so. Cheers.

**Comment by agentzh** [comment]
@ingydotnet Oh, sorry for the confusion. I'm still working on the Pegex port of opsboy locally. Nothing pushed yet. I'll let you know when I'm done.

And the opsboy tool does not have a proper test suite because it was a quick hack though I'm heavily relying on it in my test cluster for nginx/openresty/luajit.

The LZSQL compiler I mentioned on IRC is a much bigger and much more serious (company) project which has a proper test suite. I'll try to convince my former employer to allow me to opensource it. It's a good project for such experiments for its own right and can serve as a good template for other similarly complicated Perl-based compilers :)

**Comment by ingydotnet** [comment]
@agentzh great great great. Sent you email about stuff. Think I got right address.

Something like a tiny C compiler would be great for Pegex GDD (grammar driven dev!).

See this for a partial C parser for Inline::C. It only needs to parse out function defs and decls: https://github.com/ingydotnet/inline-c-pgx/blob/master/inline-c.pgx

**Comment by ingydotnet** [comment]
@agentzh, re your original thing I wonder if putting a - after the top rule would work?

    expr: add-sub -

Cleaner, but I think slower since it adds a regex to the compiled tree.
