### ISSUE TITLE
Unexpected captured data in subrules fused in a pegex regex

### ISSUE THREAD

**Issue by agentzh** [ingydotnet/pegex-pm#41]
I'm not sure if the following behavior is expected in Pegex, though it's certainly not what I want:

```perl
# a.pl
use Pegex;
use Data::Dumper;

open my $in, "a.pgx" or die $!;
my $grammar = do { local $/; <$in> };
print Dumper pegex($grammar)->parse("   print('hello')\n")
```

```
# a.pgx

lua-code-atom:
  | /(
      (: [^ SINGLE DOUBLE LCURLY RCURLY ]+
      | double-quoted-string
      | single-quoted-string
      )+
    )/

single-quoted-string: /
  (
    SINGLE
     (: BACK ANY
     | [^ BACK BREAK SINGLE ]
     )*
    SINGLE
  )
/

double-quoted-string: /
  (
    DOUBLE
     (: BACK ANY
     | [^ BACK BREAK DOUBLE ]
     )*
    DOUBLE
  )
/
```

Running `a.pl` yields

```
$VAR1 = {
          'lua_code_atom' => [
                               '   print(\'hello\')
',
                               undef,
                               '\'hello\''
                             ]
        };
```

What I want is just a single Perl string

```
'   print(\'hello\')
'
```

instead of a strange Perl array.

**Comment by ingydotnet** [comment]
Run this: https://gist.github.com/bd83fa7789fbcc44f1c9

You didn't want captures inside the subrules. You might need something like
this elsewhere:

    double-quoted-string-capture: /( double-quoted-string )/

Rule refs in a regex are just inserted after they are expanded themselves. You
had an outer capture with refs that had inner captures. I figured it out by
doing this:

    XXX pegex(<DATA>)->grammar->tree;

To see what the grammar compiled to.

**Comment by agentzh** [comment]
@ingydotnet Thanks for the hint! I've adjusted my code in lzsql via commit agentzh/lzsql@495f8a676d

**Comment by ingydotnet** [comment]
@agentzh this has convinced me that Pegex should dig deeper into regex parsing and do things like not nest (()) or [[]] and also combine /a/ | /b/ into /(:a|b)/.

Hopefully I can do this over time. Please let me know of any real showstoppers.

(comment reposted from commit above)
