### ISSUE TITLE
Optimize line_column() calls

### ISSUE THREAD

**Issue by agentzh** [ingydotnet/pegex-pm#42]
In my Pegex port of the LZSQL language parser, the `line_column` calls contribute a good amount of CPU time to the total parsing time according to the following inversed Perl-land on-CPU flame graph by sampling a busy `lzsql-compiler` perl process at real time:

http://agentzh.org/misc/flamegraph/rev-perl-land-pegex-lzsql-parser.svg

(We can ignore those unrelated function frames contributed by Moose and its underlying Class::Mop class here).

**Comment by ingydotnet** [comment]
I think the line # belongs logically to the `Pegex::Input` object. This object is supposed to be an Input abstraction, but really doesn't do much yet. I wonder if it should be removed.

So 2 thoughts:

1) Calculating the line # is going to take time no matter where it is done. It should not be done by default. Maybe the receiver object can have a `need_line_number => 1,` argument for construction. 

2) The Receiver object points to the Parser object points to the Input object. Maybe we can have a scalar ref pointing to the value in the Input object, to avoid `$receiver->parser->input->line_number` calls.

Pegex in general tries to avoid method calls. The optimizer locates the receiver functions before the parse and puts them (code refs) into the grammar object. Maybe we can go further with this strategy.

**Comment by agentzh** [comment]
@ingydotnet Good plan. Sounds cool to me :)

**Comment by agentzh** [comment]
Just FYI, I've just tested another (big) parser based on Pegex. It took 10 sec to parse a 79KB input on my mid-2016 MacBook Pro (the highest hardware spec). The Perl-land flamegraph again shows `Pegex::Parser::line_column` is dominating the performance (80.25% of the total CPU time). Ouch! :)

We'll try optimizing the `line_column` method according to your input.

**Comment by agentzh** [comment]
@ingydotnet Okay, I've just optimized the line number calculation in Pegex. My parser where `Pegex::Parser::line_column` used to take 80%+ CPU time is now more than two times faster (from 10 sec to 2.9 sec).

I'll create a pull request soon.

**Comment by perlpunk** [comment]
@agentzh Can this be closed since #52 has been merged?

**Comment by agentzh** [comment]
@perlpunk Yes.
