### ISSUE TITLE
Parse Stack

### ISSUE THREAD

**Issue by terrencehan** [ingydotnet/pegex-pm#44]
Is there any way to get parse stack in got_$rule method? If so, we can make some decision in different contexts.

**Comment by vikasnkumar** [comment]
@terrencehan, yes. Use $self->parser->stack in the got_$rule method to retrieve the current parse stack.

**Comment by ingydotnet** [comment]
Closing this, since it's not an issue. :)

@terrencehan feel free to drop by #pegex on irc.freenode.net if you have more questions!
